---
name: Makefile CI

on:
  pull_request:
    branches:       #[ master ]
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - 'master'    # includes master
      - 'main'      # includes main
  push:
    branches: [ "master", "main" , "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2

    - name: make
      run: |
          python3 -m pip install virtualenv
          make
          make help
          make report
          make all
          make venv
          make test-venv
          make init
